const $=id=>document.getElementById(id);let playerId='',roomCode='',isHost=false,currentQuestion=null,selectedOption=null,practice=null,timerInterval=null,pollInterval=null;
function show(view){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));$(view).classList.add('active');$('homeBtn').classList.toggle('hidden',view==='homeView');}
$('practiceBtn').onclick=()=>{startPractice();show('practiceView')};$('onlineBtn').onclick=()=>show('onlineView');$('practiceBack').onclick=()=>show('homeView');$('onlineBack').onclick=()=>show('homeView');$('homeBtn').onclick=()=>show('homeView');$('resultsHome').onclick=()=>show('homeView');
$('copyCode').onclick=async()=>{try{await navigator.clipboard.writeText(roomCode)}catch{}$('copyCode').textContent='✅ Copiado!';setTimeout(()=>$('copyCode').textContent='📋 Copiar código',1000)};
const els=[['H','Hidrogênio'],['He','Hélio'],['Li','Lítio'],['Be','Berílio'],['B','Boro'],['C','Carbono'],['N','Nitrogênio'],['O','Oxigênio'],['F','Flúor'],['Ne','Neônio'],['Na','Sódio'],['Mg','Magnésio'],['Al','Alumínio'],['Si','Silício'],['P','Fósforo'],['S','Enxofre'],['Cl','Cloro'],['Ar','Argônio'],['K','Potássio'],['Ca','Cálcio'],['Sc','Escândio'],['Ti','Titânio'],['V','Vanádio'],['Cr','Cromo'],['Mn','Manganês'],['Fe','Ferro'],['Co','Cobalto'],['Ni','Níquel'],['Cu','Cobre'],['Zn','Zinco'],['Ga','Gálio'],['Ge','Germânio'],['As','Arsênio'],['Se','Selênio'],['Br','Bromo'],['Kr','Criptônio'],['Rb','Rubídio'],['Sr','Estrôncio'],['Y','Ítrio'],['Zr','Zircônio'],['Nb','Nióbio'],['Mo','Molibdênio'],['Tc','Tecnécio'],['Ru','Rutênio'],['Rh','Ródio'],['Pd','Paládio'],['Ag','Prata'],['Cd','Cádmio'],['In','Índio'],['Sn','Estanho'],['Sb','Antimônio'],['Te','Telúrio'],['I','Iodo'],['Xe','Xenônio'],['Cs','Césio'],['Ba','Bário'],['La','Lantânio'],['Ce','Cério'],['Pr','Praseodímio'],['Nd','Neodímio'],['Pm','Promécio'],['Sm','Samário'],['Eu','Európio'],['Gd','Gadolínio'],['Tb','Térbio'],['Dy','Disprósio'],['Ho','Hólmio'],['Er','Érbio'],['Tm','Túlio'],['Yb','Itérbio'],['Lu','Lutécio'],['Hf','Háfnio'],['Ta','Tântalo'],['W','Tungstênio'],['Re','Rênio'],['Os','Ósmio'],['Ir','Irídio'],['Pt','Platina'],['Au','Ouro'],['Hg','Mercúrio'],['Tl','Tálio'],['Pb','Chumbo'],['Bi','Bismuto'],['Po','Polônio'],['At','Astato'],['Rn','Radônio'],['Fr','Frâncio'],['Ra','Rádio'],['Ac','Actínio'],['Th','Tório'],['Pa','Protactínio'],['U','Urânio'],['Np','Netúnio'],['Pu','Plutônio'],['Am','Amerício'],['Cm','Cúrio'],['Bk','Berquélio'],['Cf','Califórnio'],['Es','Einstênio'],['Fm','Férmio'],['Md','Mendelévio'],['No','Nobélio'],['Lr','Laurêncio'],['Rf','Rutherfórdio'],['Db','Dúbnio'],['Sg','Seabórgio'],['Bh','Bóhrio'],['Hs','Hássio'],['Mt','Meitnério'],['Ds','Darmstádio'],['Rg','Roentgênio'],['Cn','Copernício'],['Nh','Nihônio'],['Fl','Fleróvio'],['Mc','Moscóvio'],['Lv','Livermório'],['Ts','Tenessino'],['Og','Oganessônio']].map(([symbol,name])=>({symbol,name}));
const defs=[{p:'O que é um átomo?',o:['A menor unidade de um elemento químico que mantém suas propriedades químicas.','Uma tabela que organiza os elementos.','Uma mistura de substâncias.','Uma molécula com dois átomos.'],a:0},{p:'O que é a tabela periódica?',o:['Uma lista aleatória de substâncias.','Uma organização dos elementos químicos por número atômico e propriedades.','Uma tabela só de metais.','Um desenho somente de átomos estáveis.'],a:1}];const pick=a=>a[Math.floor(Math.random()*a.length)];const norm=s=>String(s??'').trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]/g,'');
function makeLocalQuestion(){const r=Math.random(),e=pick(els);if(r<.4)return{p:`Qual é o símbolo químico de <strong>${e.name}</strong>?`,a:e.symbol,mode:'text',tag:'NOME → SÍMBOLO'};if(r<.8)return{p:`Qual elemento corresponde ao símbolo <strong>${e.symbol}</strong>?`,a:e.name,mode:'text',tag:'SÍMBOLO → NOME'};const d=pick(defs);return{p:d.p,o:d.o,a:d.a,mode:'choice',tag:'CONCEITOS'}}
function startPractice(){practice={n:0,total:10,score:0,streak:0,questions:Array.from({length:10},makeLocalQuestion)};renderPractice()}
function renderPractice(){const q=practice.questions[practice.n];$('practiceProgress').textContent=`${practice.n+1} / ${practice.total}`;$('practiceBar').style.width=`${((practice.n+1)/practice.total)*100}%`;$('practicePrompt').innerHTML=q.p;$('practiceType').textContent=q.tag;$('practiceScore').textContent=practice.score;$('practiceStreak').textContent=practice.streak;$('practiceFeedback').textContent='';$('practiceSubmit').textContent='Responder';$('practiceSubmit').disabled=false;selectedOption=null;if(q.mode==='text')$('practiceAnswerArea').innerHTML='<input id="practiceInput" class="answer-input" placeholder="Digite sua resposta..." autocomplete="off">';else{$('practiceAnswerArea').innerHTML=q.o.map((x,i)=>`<button class="option" data-i="${i}">${x}</button>`).join('');document.querySelectorAll('#practiceAnswerArea .option').forEach(btn=>btn.onclick=()=>{selectedOption=Number(btn.dataset.i);document.querySelectorAll('#practiceAnswerArea .option').forEach(b=>b.classList.remove('selected'));btn.classList.add('selected')})}if(q.mode==='text')$('practiceInput').focus()}
$('practiceSubmit').onclick=()=>{if(practice.n>=practice.total)return;const q=practice.questions[practice.n];let correct=q.mode==='text'?norm($('practiceInput').value)===norm(q.a):selectedOption===q.a;const f=$('practiceFeedback');if(correct){practice.score+=100+practice.streak*10;practice.streak++;f.textContent='✅ Acertou!';f.className='feedback ok'}else{practice.streak=0;f.textContent='❌ Resposta: '+(q.mode==='text'?q.a:q.o[q.a]);f.className='feedback bad'}$('practiceScore').textContent=practice.score;$('practiceStreak').textContent=practice.streak;$('practiceSubmit').disabled=true;setTimeout(()=>{if(practice.n<practice.total-1){practice.n++;renderPractice()}else{f.textContent=`🏆 Treino finalizado! Você fez ${practice.score} pontos.`;$('practiceSubmit').textContent='Recomeçar';$('practiceSubmit').disabled=false;$('practiceSubmit').onclick=()=>{startPractice()}}},650)};
async function post(path,data){const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});return r.json()}
async function enterFromResult(result){playerId=result.playerId;roomCode=result.code;isHost=result.hostId===playerId;show('lobbyView');startPolling()}
function showOnlineError(msg){$('onlineError').textContent=msg;$('onlineError').className='feedback error'}
$('createBtn').onclick=async()=>{const name=$('createName').value.trim();if(!name)return showOnlineError('Digite um apelido.');const r=await post('/api/create',{name,questionCount:Number($('questionCount').value),mode:$('mode').value});if(!r.ok)return showOnlineError(r.error);await enterFromResult(r)};
$('joinBtn').onclick=async()=>{const name=$('joinName').value.trim(),code=$('roomCode').value.trim().toUpperCase();if(!name||!code)return showOnlineError('Preencha apelido e código.');const r=await post('/api/join',{name,code});if(!r.ok)return showOnlineError(r.error);await enterFromResult(r)};
$('startBtn').onclick=async()=>{const r=await post('/api/start',{code:roomCode,playerId});if(!r.ok)alert(r.error)};
function startPolling(){clearInterval(pollInterval);refreshRoom();pollInterval=setInterval(refreshRoom,700)}
async function refreshRoom(){if(!roomCode)return;const r=await fetch('/api/room?code='+encodeURIComponent(roomCode)+'&playerId='+encodeURIComponent(playerId),{cache:'no-store'}).then(x=>x.json()).catch(()=>null);if(!r?.ok){clearInterval(pollInterval);return}renderRoom(r.room);if(r.room.started&&!currentQuestion){await waitForQuestion();}}
function renderRoom(state){$('lobbyCode').textContent=state.code;$('playerCount').textContent=state.players.length;$('playersList').innerHTML=state.players.map(p=>`<div class="player-chip"><span class="player-dot ${p.answered?'ready':''}"></span><span>${escapeHtml(p.name)}</span></div>`).join('');isHost=state.hostId===playerId;if(!state.started){$('startBtn').classList.toggle('hidden',!isHost);$('hostHint').textContent=isHost?'Você é o criador. Clique para começar!':'Aguardando o criador começar a partida.'}else{$('startBtn').classList.add('hidden')}}
async function waitForQuestion(){const r=await fetch('/api/room?code='+encodeURIComponent(roomCode)+'&playerId='+encodeURIComponent(playerId),{cache:'no-store'}).then(x=>x.json()).catch(()=>null);if(!r?.ok)return;if(r.room.started){const q=await fetch('/api/question?code='+encodeURIComponent(roomCode)+'&playerId='+encodeURIComponent(playerId),{cache:'no-store'}).then(x=>x.json()).catch(()=>null);if(q?.ok&&q.question)receiveQuestion(q.question)}}
async function loadQuestion(){const r=await fetch('/api/question?code='+encodeURIComponent(roomCode)+'&playerId='+encodeURIComponent(playerId),{cache:'no-store'}).then(x=>x.json()).catch(()=>null);if(r?.ok&&r.question)receiveQuestion(r.question);return r}
function receiveQuestion(q){currentQuestion=q;selectedOption=null;show('gameView');$('roundLabel').textContent=`Pergunta ${q.number} / ${q.total}`;$('questionPrompt').innerHTML=q.prompt;$('questionTag').textContent=q.type==='definition'?'CONCEITOS':q.type==='name-to-symbol'?'NOME → SÍMBOLO':q.type==='symbol-to-name'?'SÍMBOLO → NOME':'DESAFIO';$('gameBar').style.width=`${q.number/q.total*100}%`;$('gameFeedback').textContent='';$('gameFeedback').className='feedback';$('gameSubmit').disabled=false;if(q.inputMode==='choice'){$('gameAnswerArea').innerHTML=q.options.map((x,i)=>`<button class="option" data-i="${i}">${x}</button>`).join('');document.querySelectorAll('#gameAnswerArea .option').forEach(btn=>btn.onclick=()=>{selectedOption=Number(btn.dataset.i);document.querySelectorAll('#gameAnswerArea .option').forEach(b=>b.classList.remove('selected'));btn.classList.add('selected')})}else{$('gameAnswerArea').innerHTML=`<input id="gameInput" class="answer-input" placeholder="${escapeHtml(q.hint||'Digite sua resposta...')}" autocomplete="off">`;$('gameInput').focus()}startTimer(q.deadline)}
$('gameSubmit').onclick=async()=>{if(!currentQuestion)return;let value='',index=null;if(currentQuestion.inputMode==='choice'){index=selectedOption;if(index===null){$('gameFeedback').textContent='Escolha uma alternativa.';return}}else value=$('gameInput').value.trim();const r=await post('/api/answer',{code:roomCode,playerId,value,index});if(!r.ok){$('gameFeedback').textContent=r.error;return}$('gameSubmit').disabled=true;$('gameFeedback').textContent=r.correct?'✅ Acertou!':'❌ Errou!';$('gameFeedback').className='feedback '+(r.correct?'ok':'bad');setTimeout(async()=>{const q=await loadQuestion();if(q?.roundResult)renderRoundResult(q.roundResult)},450)};
async function loadQuestionOrResult(){const r=await loadQuestion();if(r?.roundResult)renderRoundResult(r.roundResult);if(r?.gameOver)renderGameOver(r.gameOver);return r}
async function pollGame(){const r=await loadQuestionOrResult();if(r?.question&&(!currentQuestion||r.question.number!==currentQuestion.number))receiveQuestion(r.question);if(r?.roundResult)renderRoundResult(r.roundResult);if(r?.gameOver)renderGameOver(r.gameOver)}
function renderRoundResult(rr){if(!currentQuestion)return;$('gameFeedback').textContent=`Resposta: ${rr.correctAnswer}`;$('gameFeedback').className='feedback';renderLive(rr.standings)}
function renderLive(rows){$('liveList').innerHTML=(rows||[]).map(p=>`<div class="live-row"><div><div class="live-name">${escapeHtml(p.name)}</div><div class="live-status">${p.id===playerId?'Você':''}</div></div><b>${p.score}</b></div>`).join('');$('answeredCount').textContent=(rows||[]).filter(x=>x.answered).length+' responderam'}
function renderGameOver(data){clearInterval(timerInterval);$('resultsPodium').innerHTML=data.standings.slice(0,3).map((p,i)=>`<div class="podium-item ${['first','second','third'][i]||''}"><div class="place">${['🥇','🥈','🥉'][i]||'🏅'}</div><b>${escapeHtml(p.name)}</b><span>${p.score} pontos</span></div>`).join('');$('finalList').innerHTML=data.standings.map(p=>`<div class="final-row"><span><b>${p.place}º</b> ${escapeHtml(p.name)}</span><strong>${p.score}</strong></div>`).join('');show('resultsView')}
function startTimer(deadline){clearInterval(timerInterval);const tick=()=>{const n=Math.max(0,Math.ceil((deadline-Date.now())/1000));$('timer').textContent=n;if(n<=0)clearInterval(timerInterval)};tick();timerInterval=setInterval(tick,250)}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
setInterval(()=>{if(roomCode&&$('gameView').classList.contains('active'))pollGame()},800);
